Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,12 +37,12 @@ jobs:
         echo "Compiling: blocklist"
         sing-box version
         ls
-        sing-box rule-set convert --type adguard blocklist.txt
-        #if ! sing-box rule-set convert --type adguard blocklist.txt; then
-         # echo "Error compiling blocklist"
-         # exit 1
-        #fi
-        rm -rf blocklist.txt
+        #sing-box rule-set convert --type adguard blocklist.txt
+        if ! sing-box rule-set convert --type adguard blocklist.txt; then
+          echo "Error compiling blocklist"
+          exit 1
+        fi
+        #rm -rf blocklist.txt
         
     # 将下载的文件添加到 git，并提交
     - name: Commit and Push changes
