Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,10 +37,11 @@ jobs:
         echo "Compiling: blocklist"
         sing-box version
         ls
-        if ! sing-box rule-set convert --type adguard blocklist.txt; then
-          echo "Error compiling blocklist"
-          exit 1
-        fi
+        sing-box rule-set convert --type adguard blocklist.txt
+        #if ! sing-box rule-set convert --type adguard blocklist.txt; then
+         # echo "Error compiling blocklist"
+         # exit 1
+        #fi
         rm -rf blocklist.txt
         
     # 将下载的文件添加到 git，并提交
